import { getStemBranchForLunarYear, STEM_ELEMENT, BRANCH_ANIMAL, getYearEnergyRelationship, HEAVENLY_STEMS, EARTHLY_BRANCHES, FIVE_ELEMENTS } from './eastern-horoscope-tables';

/**
 * Full-coverage golden vectors (G1–G12, `docs/domain/eastern-horoscope-rules.md` §8b) — 12
 * consecutive Tết-anchored lunar years, chosen because 12 consecutive draws from a 10-Stem/12-Branch
 * cycle mathematically guarantee full coverage of all 10 Stems, all 12 Branches/animals, and (via
 * the Stem→Element table) all 5 Elements and both Yin/Yang. Every Stem-Chi/animal/element value is
 * independently sourced this sprint (5 years directly, 7 via Tết-animal-list + verified cycle
 * arithmetic) — never generated by this engine.
 */
describe('getStemBranchForLunarYear — 12-year full-coverage golden vectors (G1–G12)', () => {
  const vectors: Array<{ lunarYear: number; stem: string; branch: string; element: string; yinYang: string; enAnimal: string }> = [
    { lunarYear: 2013, stem: 'Quý', branch: 'Tỵ', element: 'Thủy', yinYang: 'Âm', enAnimal: 'Snake' },
    { lunarYear: 2014, stem: 'Giáp', branch: 'Ngọ', element: 'Mộc', yinYang: 'Dương', enAnimal: 'Horse' },
    { lunarYear: 2015, stem: 'Ất', branch: 'Mùi', element: 'Mộc', yinYang: 'Âm', enAnimal: 'Goat' },
    { lunarYear: 2016, stem: 'Bính', branch: 'Thân', element: 'Hỏa', yinYang: 'Dương', enAnimal: 'Monkey' },
    { lunarYear: 2017, stem: 'Đinh', branch: 'Dậu', element: 'Hỏa', yinYang: 'Âm', enAnimal: 'Rooster' },
    { lunarYear: 2018, stem: 'Mậu', branch: 'Tuất', element: 'Thổ', yinYang: 'Dương', enAnimal: 'Dog' },
    { lunarYear: 2019, stem: 'Kỷ', branch: 'Hợi', element: 'Thổ', yinYang: 'Âm', enAnimal: 'Pig' },
    { lunarYear: 2020, stem: 'Canh', branch: 'Tý', element: 'Kim', yinYang: 'Dương', enAnimal: 'Rat' },
    { lunarYear: 2021, stem: 'Tân', branch: 'Sửu', element: 'Kim', yinYang: 'Âm', enAnimal: 'Ox' },
    { lunarYear: 2022, stem: 'Nhâm', branch: 'Dần', element: 'Thủy', yinYang: 'Dương', enAnimal: 'Tiger' },
    { lunarYear: 2023, stem: 'Quý', branch: 'Mão', element: 'Thủy', yinYang: 'Âm', enAnimal: 'Cat' },
    { lunarYear: 2024, stem: 'Giáp', branch: 'Thìn', element: 'Mộc', yinYang: 'Dương', enAnimal: 'Dragon' },
  ];

  it.each(vectors)('lunar year $lunarYear -> $stem $branch ($element, $yinYang), animal=$enAnimal', ({ lunarYear, stem, branch, element, yinYang, enAnimal }) => {
    const result = getStemBranchForLunarYear(lunarYear);
    expect(result.stem).toBe(stem);
    expect(result.branch).toBe(branch);
    expect(STEM_ELEMENT[result.stem].element).toBe(element);
    expect(STEM_ELEMENT[result.stem].yinYang).toBe(yinYang);
    expect(BRANCH_ANIMAL[result.branch].en).toBe(enAnimal);
  });

  it('covers all 10 Heavenly Stems across the 12-year window', () => {
    const stems = new Set(vectors.map((v) => getStemBranchForLunarYear(v.lunarYear).stem));
    expect(stems.size).toBe(10);
    for (const stem of HEAVENLY_STEMS) expect(stems.has(stem)).toBe(true);
  });

  it('covers all 12 Earthly Branches / zodiac animals across the 12-year window', () => {
    const branches = new Set(vectors.map((v) => getStemBranchForLunarYear(v.lunarYear).branch));
    expect(branches.size).toBe(12);
    for (const branch of EARTHLY_BRANCHES) expect(branches.has(branch)).toBe(true);
  });

  it('covers all 5 Elements across the 12-year window', () => {
    const elements = new Set(vectors.map((v) => STEM_ELEMENT[getStemBranchForLunarYear(v.lunarYear).stem].element));
    expect(elements.size).toBe(5);
    for (const element of FIVE_ELEMENTS) expect(elements.has(element)).toBe(true);
  });

  it('covers both Yin and Yang across the 12-year window', () => {
    const polarities = new Set(vectors.map((v) => STEM_ELEMENT[getStemBranchForLunarYear(v.lunarYear).stem].yinYang));
    expect(polarities).toEqual(new Set(['Dương', 'Âm']));
  });

  it('1984 is the anchor year, Giáp Tý (independently cross-checked this sprint)', () => {
    const result = getStemBranchForLunarYear(1984);
    expect(result.stem).toBe('Giáp');
    expect(result.branch).toBe('Tý');
  });

  it('1986 is Bính Dần (independently sourced this sprint)', () => {
    const result = getStemBranchForLunarYear(1986);
    expect(result.stem).toBe('Bính');
    expect(result.branch).toBe('Dần');
  });
});

describe('EH-04 verification — the locked canonical element genuinely differs from popular Nạp Âm "mệnh" for real years', () => {
  it('1984 (Giáp Tý): canonical element is Mộc (Wood), not the popularly-cited Nạp Âm Kim (Metal)', () => {
    expect(STEM_ELEMENT[getStemBranchForLunarYear(1984).stem].element).toBe('Mộc');
  });

  it('2024 (Giáp Thìn): canonical element is Mộc (Wood) — matches the Bible module\'s own "Wood Dragon year" worked example', () => {
    expect(STEM_ELEMENT[getStemBranchForLunarYear(2024).stem].element).toBe('Mộc');
  });
});

describe('getYearEnergyRelationship — Five Elements generating/controlling cycle (fixed, non-disputed)', () => {
  it('each element generates the next in the fixed cycle: Mộc->Hỏa->Thổ->Kim->Thủy->Mộc', () => {
    expect(getYearEnergyRelationship('Mộc', 'Hỏa')).toBe('GENERATES');
    expect(getYearEnergyRelationship('Hỏa', 'Thổ')).toBe('GENERATES');
    expect(getYearEnergyRelationship('Thổ', 'Kim')).toBe('GENERATES');
    expect(getYearEnergyRelationship('Kim', 'Thủy')).toBe('GENERATES');
    expect(getYearEnergyRelationship('Thủy', 'Mộc')).toBe('GENERATES');
  });

  it('the inverse of GENERATES is IS_GENERATED_BY', () => {
    expect(getYearEnergyRelationship('Hỏa', 'Mộc')).toBe('IS_GENERATED_BY');
  });

  it('each element controls the element two steps ahead: Mộc->Thổ->Thủy->Hỏa->Kim->Mộc', () => {
    expect(getYearEnergyRelationship('Mộc', 'Thổ')).toBe('CONTROLS');
    expect(getYearEnergyRelationship('Thổ', 'Thủy')).toBe('CONTROLS');
    expect(getYearEnergyRelationship('Thủy', 'Hỏa')).toBe('CONTROLS');
    expect(getYearEnergyRelationship('Hỏa', 'Kim')).toBe('CONTROLS');
    expect(getYearEnergyRelationship('Kim', 'Mộc')).toBe('CONTROLS');
  });

  it('the inverse of CONTROLS is IS_CONTROLLED_BY', () => {
    expect(getYearEnergyRelationship('Thổ', 'Mộc')).toBe('IS_CONTROLLED_BY');
  });

  it('the same element relates as SAME', () => {
    expect(getYearEnergyRelationship('Mộc', 'Mộc')).toBe('SAME');
  });
});
