import { convertSolarToLunar, getLunarYearForGregorianDate } from './lunar-calendar.adapter';

/**
 * Golden vectors — every expected value below is independently sourced (Vietnamese-holiday
 * reference lookups via live web search, this sprint), never generated by this engine. See
 * `docs/domain/eastern-horoscope-rules.md` §8a for full sourcing detail and rationale per vector.
 * Per the Sprint 17 implementation brief: if any of these ever disagree with the implementation,
 * the correct response is to investigate the implementation/source, never to edit the expected
 * value to make the test pass.
 */
describe('convertSolarToLunar — 13 independently-sourced real Lunar New Year (Tết) dates', () => {
  const knownTet: Array<[gregorianYear: number, month: number, day: number]> = [
    [2013, 2, 10],
    [2014, 1, 31],
    [2015, 2, 19],
    [2016, 2, 8],
    [2017, 1, 28],
    [2018, 2, 16],
    [2019, 2, 5],
    [2020, 1, 25],
    [2021, 2, 12],
    [2022, 2, 1],
    [2023, 1, 22],
    [2024, 2, 10],
    [2025, 1, 29],
  ];

  it.each(knownTet)('Tết %i falls on the sourced Gregorian date %i-%i and resolves to lunar month 1, day 1, non-leap', (year, month, day) => {
    const result = convertSolarToLunar(day, month, year, 7);
    expect(result).toEqual({ lunarDay: 1, lunarMonth: 1, lunarYear: year, lunarLeap: false });
  });
});

describe('convertSolarToLunar — boundary-behavior golden vectors (docs/domain/eastern-horoscope-rules.md §8a)', () => {
  it('B1: 2024-02-09, the day immediately before Tết, is still lunar year 2023 (Quý Mão)', () => {
    expect(convertSolarToLunar(9, 2, 2024, 7).lunarYear).toBe(2023);
  });

  it('B2: 2024-02-10, Tết itself, is lunar year 2024 (Giáp Thìn)', () => {
    expect(convertSolarToLunar(10, 2, 2024, 7).lunarYear).toBe(2024);
  });

  it('B3: 2024-02-11, the day immediately after Tết, is still lunar year 2024', () => {
    expect(convertSolarToLunar(11, 2, 2024, 7).lunarYear).toBe(2024);
  });

  it('B4: 2024-01-01 (Gregorian January 1) does NOT trigger a year change — still lunar year 2023', () => {
    expect(convertSolarToLunar(1, 1, 2024, 7).lunarYear).toBe(2023);
  });

  it('B5: 2015-02-10 — after Lập Xuân (2015-02-04) but before Tết (2015-02-19) — remains lunar year 2014 (Giáp Ngọ), proving the locked LUNAR_NEW_YEAR convention (not Lập Xuân) is actually implemented', () => {
    expect(convertSolarToLunar(10, 2, 2015, 7).lunarYear).toBe(2014);
  });
});

describe('convertSolarToLunar — leap lunar year (L1, docs/domain/eastern-horoscope-rules.md §8c)', () => {
  it('2020 (Canh Tý) had a leap 4th lunar month; a date within it is still correctly lunar year 2020', () => {
    const result = convertSolarToLunar(23, 2, 2020, 7);
    expect(result.lunarYear).toBe(2020);
  });
});

describe('getLunarYearForGregorianDate — Date-object entry point', () => {
  it('matches convertSolarToLunar for the same date', () => {
    expect(getLunarYearForGregorianDate(new Date('2024-02-10T00:00:00.000Z'))).toBe(2024);
    expect(getLunarYearForGregorianDate(new Date('2024-02-09T00:00:00.000Z'))).toBe(2023);
    expect(getLunarYearForGregorianDate(new Date('2024-01-01T00:00:00.000Z'))).toBe(2023);
  });
});
