import type { Metadata } from 'next';
import { buildMetadata } from '@/lib/seo';
import { MvPage, MvPageHeader, MvSection } from '@/components/ui/mv-page';

export const metadata: Metadata = buildMetadata({
  title: 'Privacy Notice',
  description: 'How Tử Vi Tarot handles your data — what is collected, how it is used, and your rights to export or delete it.',
  path: '/privacy',
});

/** A fact only the founder or an authorized legal reviewer can supply — never invented here. See
 * docs/progress/legal-content-completion-final-report.md for the full founder/legal decision
 * register this corresponds to. */
function OwnerPlaceholder({ children }: { children: React.ReactNode }) {
  return <span className="italic text-text-tertiary">[Owner/Legal to confirm: {children}]</span>;
}

const LAST_UPDATED = '2026-08-22';

export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-content px-4 py-16 desktop:px-8">
      <MvPage>
        <MvPageHeader
          eyebrow="Quyền riêng tư"
          title="Privacy Notice"
          description="How Tử Vi Tarot handles your data and the controls available to you."
        />
        <p className="text-body-sm text-text-tertiary">Last updated: {LAST_UPDATED}.</p>

        <MvSection title="1. Who operates this service">
          <p className="text-body-md text-text-secondary">
            Tử Vi Tarot (<OwnerPlaceholder>the legal entity name and registration details that operate this service</OwnerPlaceholder>,
            operating at <OwnerPlaceholder>registered business address</OwnerPlaceholder>) provides this website and app. This notice
            explains what we collect through it, why, and what control you have.
          </p>
        </MvSection>

        <MvSection title="2. Information you provide">
          <p className="text-body-md text-text-secondary">When you create an account, we collect your email address, a display name, and a password
            (stored only as a salted cryptographic hash — we never store or can recover your plaintext password). Depending on which
            features you use, you may also enter birth or personal details directly into a specific Discovery feature — see §4.
          </p>
        </MvSection>

        <MvSection title="3. Information generated by the service">
          <p className="text-body-md text-text-secondary">
            Using the product creates records tied to your account: the results of any Discovery calculation you run, any AI
            interpretation generated for it, your Companion conversation history, Memory notes, Journal entries, notifications, and
            a basic activity log (e.g., which feature you used and when). These are the same records you can review, export, or
            delete at any time — see §13–§14.
          </p>
        </MvSection>

        <MvSection title="4. Birth information and astrology-related inputs">
          <ul className="list-disc space-y-2 pl-5 text-body-md text-text-secondary">
            <li><strong>Tử Vi Lá Số</strong> — date of birth, time of birth, and sex, used to compute your chart.</li>
            <li><strong>Natal Chart</strong> — date of birth, time of birth (or an approximate/unknown-time option), and place of
              birth. A place-of-birth search sends your typed search text to the public OpenStreetMap Nominatim service to resolve
              coordinates — see §16.</li>
            <li><strong>Numerology</strong> — your full birth name and date of birth.</li>
            <li><strong>Eastern Horoscope</strong> — date of birth.</li>
          </ul>
          <p className="mt-3 text-body-md text-text-secondary">
            Every one of these results — the chart, the numbers, the placements, the animal sign — is calculated by a deterministic,
            non-AI engine specific to that system. AI never determines, chooses, or alters any of these facts; see §6.
          </p>
        </MvSection>

        <MvSection title="5. Tarot readings">
          <p className="text-body-md text-text-secondary">
            A Tarot draw (card and orientation) is generated by a real, non-AI randomization process and saved to your reading
            history along with any reflection or interpretation attached to it, so you can revisit it later.
          </p>
        </MvSection>

        <MvSection title="6. AI processing">
          <p className="text-body-md text-text-secondary">
            After a Discovery result (Tarot, Numerology, Natal Chart, Eastern Horoscope, or Tử Vi) is calculated, we send the
            already-computed facts to an AI provider to generate a plain-language narrative explaining that result. The AI never
            performs the calculation itself and cannot change a card, a number, a chart placement, or a Tử Vi star position — the
            deterministic engine&rsquo;s output is fixed before the AI ever sees it. The Companion feature is a separate, ongoing AI
            conversation: your messages to it are sent to the same AI provider to generate a reply.
          </p>
          <p className="mt-3 text-body-md text-text-secondary">
            The active AI provider is one of OpenAI, Anthropic, or Google (Gemini), configured per deployment — only one is active
            at a time, and a local-only mock provider (never real AI, never used in production) exists solely for development. We do
            not use your conversations or readings to train AI models without your explicit, specific, separately-requested consent.
          </p>
        </MvSection>

        <MvSection title="7. Analytics">
          <p className="text-body-md text-text-secondary">
            When product analytics is enabled, we record a small, fixed set of event properties — which feature you used, the page
            path (never the full URL, query string, or referrer), whether an action succeeded, and similar coarse signals. This
            never includes free-text content, birth data, journal or message content, or anything from a Discovery reading itself.
            Before you sign in, events are tied to a random identifier stored on your device; after you sign in, they&rsquo;re tied to
            your account so we can understand real usage, not fabricate it from guesses.
          </p>
        </MvSection>

        <MvSection title="8. Error monitoring">
          <p className="text-body-md text-text-secondary">
            When error monitoring is enabled, technical error reports (what failed and where, not your data) may be sent to our
            error-monitoring provider to help us fix bugs. Reports are filtered to a fixed allowlist of operational fields — request
            bodies, cookies, query strings, and free-text content are never included, regardless of what they contain.
          </p>
        </MvSection>

        <MvSection title="9. Authentication, sessions, and security data">
          <p className="text-body-md text-text-secondary">
            Signing in issues a short-lived access token and a longer-lived refresh token, held in secure, browser-inaccessible
            (HttpOnly) cookies — never in a form JavaScript on the page (including any injected by a third party) can read. We
            briefly use your IP address to apply rate limits against repeated failed sign-in attempts, to protect all accounts from
            automated password-guessing.
          </p>
        </MvSection>

        <MvSection title="10. Payments">
          <p className="text-body-md text-text-secondary">
            Premium payments are processed by PayOS. We never receive or store your card number or full payment credentials — PayOS
            handles that directly. We keep a record of the transaction itself (amount, currency, status, and timestamps) for
            accounting purposes, even after account deletion; see §14 and §15.
          </p>
        </MvSection>

        <MvSection title="11. Community and user-generated content shared with others">
          <p className="text-body-md text-text-secondary">
            Tử Vi Tarot has no public or shared community feature today — your readings, journal, and conversations are visible only
            to you (and to us, as described in this notice). If that changes in the future, this notice will be updated first.
          </p>
        </MvSection>

        <MvSection title="12. Cookies and local storage">
          <p className="text-body-md text-text-secondary">
            We use one essential cookie to keep you signed in securely (see §9). When analytics is enabled, an anonymous identifier
            is stored on your device (see §7). We don&rsquo;t set marketing, advertising, or cross-site tracking cookies.
          </p>
        </MvSection>

        <MvSection title="13. Exporting your data">
          <p className="text-body-md text-text-secondary">
            From Settings, you can request a full export of your account data — a single file containing your account details,
            Companion conversations, Memory, Journal, every Discovery reading (Tarot, Numerology, Natal Chart, Eastern Horoscope, Tử
            Vi Lá Số), Personal Destiny Reports, notifications, and Premium/payment history. Internal fields such as your password
            hash are never included.
          </p>
        </MvSection>

        <MvSection title="14. Deleting your account">
          <p className="text-body-md text-text-secondary">
            From Settings, with your password to confirm, you can delete your account at any time. This immediately and irreversibly
            removes your Companion conversations, Memory, Journal entries, notifications, and every Discovery reading (Tarot,
            Numerology, Natal Chart, Eastern Horoscope, and Tử Vi Lá Số), along with your Personal Destiny Reports, and ends your
            Premium access. Your account identity (email, display name) is scrubbed and cannot be recovered.
          </p>
          <p className="mt-3 text-body-md text-text-secondary">
            We keep a record of past payment transactions after deletion, for accounting purposes — this record no longer carries
            any personal profile information once your account is deleted.
          </p>
        </MvSection>

        <MvSection title="15. How long we keep data">
          <p className="text-body-md text-text-secondary">
            Account and Discovery content is kept until you delete it or your account, whichever comes first — there is no
            automatic expiry. An exported data file is only cached briefly (currently 15 minutes) before you must request a new
            one. Sign-in sessions expire and must be refreshed periodically.
          </p>
          <p className="mt-3 text-body-md text-text-secondary">
            <OwnerPlaceholder>the exact retention period for payment/accounting records kept after account deletion, and any other
            retention schedule required by applicable tax, accounting, or financial-services law</OwnerPlaceholder>.
          </p>
        </MvSection>

        <MvSection title="16. Third-party processors">
          <p className="text-body-md text-text-secondary">The following outside providers can receive limited data on our behalf, only for the purpose described. Not every
            provider below is necessarily active at any given time — some are only enabled once we&rsquo;ve configured them for
            production use.
          </p>
          <ul className="mt-3 list-disc space-y-2 pl-5 text-body-md text-text-secondary">
            <li><strong>AI interpretation/Companion</strong> — one of OpenAI, Anthropic, or Google (Gemini), receiving the specific content described in §6.</li>
            <li><strong>Place-of-birth search (Natal Chart only)</strong> — OpenStreetMap Nominatim, receiving your typed search text.</li>
            <li><strong>Payments</strong> — PayOS, receiving your checkout details directly (never routed through our servers).</li>
            <li><strong>Email delivery</strong> — an email provider, for account verification, password reset, and notification emails you&rsquo;ve opted into, receiving your email address and the message content.</li>
            <li><strong>Error monitoring</strong> (when enabled) — receiving the scrubbed technical data described in §8.</li>
            <li><strong>Product analytics</strong> (when enabled) — receiving the coarse event data described in §7.</li>
            <li><strong>Hosting</strong> — <OwnerPlaceholder>the hosting/infrastructure provider once chosen</OwnerPlaceholder>, which stores the underlying database and runs the application.</li>
          </ul>
        </MvSection>

        <MvSection title="17. Security">
          <p className="text-body-md text-text-secondary">
            Passwords are stored as salted cryptographic hashes, never in plain text. Sessions use secure, browser-inaccessible
            cookies. Requests that change your data require a matching anti-forgery token. We apply rate limits to sensitive
            endpoints (sign-in, payments, AI usage) to reduce abuse. No security measure is perfect, and we can&rsquo;t guarantee
            absolute security — but we don&rsquo;t treat this as a checkbox either.
          </p>
        </MvSection>

        <MvSection title="18. Minimum age">
          <p className="text-body-md text-text-secondary">
            <OwnerPlaceholder>the minimum age required to create an account, and any parental-consent handling if the product is
            intended to be accessible to minors in some jurisdictions</OwnerPlaceholder>. The product does not currently ask for or
            verify a user&rsquo;s age at registration.
          </p>
        </MvSection>

        <MvSection title="19. Your rights">
          <p className="text-body-md text-text-secondary">
            You can access, export (§13), correct, or delete (§14) your data at any time from Settings, without needing to contact
            us first. <OwnerPlaceholder>which specific statutory rights (e.g., under Vietnamese, EU/GDPR, or other applicable data
            protection law) apply to you, and how to exercise any right not already self-service in Settings</OwnerPlaceholder>.
          </p>
        </MvSection>

        <MvSection title="20. International processing">
          <p className="text-body-md text-text-secondary">
            Some of the providers listed in §16 (AI interpretation, email delivery, error monitoring, analytics) may process data
            outside Vietnam. <OwnerPlaceholder>the specific countries involved, and the legal transfer mechanism or safeguard that
            applies to each, once providers and hosting are finalized</OwnerPlaceholder>.
          </p>
        </MvSection>

        <MvSection title="21. Changes to this notice">
          <p className="text-body-md text-text-secondary">
            If we make a material change to how we handle your data, we&rsquo;ll update this page and the date at the top of it. We
            encourage checking back periodically, especially before a significant new feature launch.
          </p>
        </MvSection>

        <MvSection title="22. Contact">
          <p className="text-body-md text-text-secondary">
            Questions about this notice or your data can be sent via the <a href="/contact" className="text-insight underline">Contact page</a>.
            <OwnerPlaceholder>a real, monitored support address to replace the current placeholder contact address</OwnerPlaceholder>.
          </p>
        </MvSection>
      </MvPage>
    </main>
  );
}
