/**
 * Mobile Home art registry — mirrors the shape of
 * apps/web/features/dashboard/components/home/production-assets.ts, but points at the mobile
 * derivatives under assets/images/home/ (generated by scripts/generate-mobile-home-assets.mjs
 * from the SAME production board Web uses; the web originals are never modified — see that
 * script's header comment for the exact crop/derivation logic).
 */

import type { ImageSource } from 'expo-image';

export type DiscoveryModuleKey = 'tu_vi' | 'tarot' | 'natal_chart' | 'numerology';

export const HOME_BACKGROUND: { hero: ImageSource; journeyBanner: ImageSource } = {
  hero: require('../../../assets/images/home/backgrounds/hero-home-mobile.webp'),
  journeyBanner: require('../../../assets/images/home/backgrounds/journey-banner-mobile.webp'),
};

export const FEATURE_ART_ASSET: Record<DiscoveryModuleKey, ImageSource> = {
  tu_vi: require('../../../assets/images/home/feature-art/tu-vi.webp'),
  tarot: require('../../../assets/images/home/feature-art/tarot.webp'),
  natal_chart: require('../../../assets/images/home/feature-art/ban-do-sao.webp'),
  numerology: require('../../../assets/images/home/feature-art/than-so-hoc.webp'),
};

export const FEATURE_BADGE_ASSET: Record<DiscoveryModuleKey, ImageSource> = {
  tu_vi: require('../../../assets/images/home/hero-overlays/tu-vi-wheel.webp'),
  tarot: require('../../../assets/images/home/hero-overlays/tarot-stack.webp'),
  natal_chart: require('../../../assets/images/home/hero-overlays/astrology-wheel.webp'),
  numerology: require('../../../assets/images/home/hero-overlays/numerology-orb.webp'),
};
