import type { Metadata } from 'next';
import { buildMetadata } from '@/lib/seo';
import { MvPage, MvPageHeader, MvSection } from '@/components/ui/mv-page';

export const metadata: Metadata = buildMetadata({
  title: 'Terms of Service',
  description: 'The terms governing your use of Tử Vi Tarot.',
  path: '/terms',
});

/** A fact only the founder or an authorized legal reviewer can supply — never invented here. See
 * docs/progress/legal-content-completion-final-report.md for the full founder/legal decision
 * register this corresponds to. */
function OwnerPlaceholder({ children }: { children: React.ReactNode }) {
  return <span className="italic text-text-tertiary">[Owner/Legal to confirm: {children}]</span>;
}

const LAST_UPDATED = '2026-08-22';

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-content px-4 py-16 desktop:px-8">
      <MvPage>
        <MvPageHeader eyebrow="Điều khoản" title="Terms of Service" description="The terms governing your use of Tử Vi Tarot." />
        <p className="text-body-sm text-text-tertiary">Last updated: {LAST_UPDATED}.</p>

        <MvSection title="1. The service">
          <p className="text-body-md text-text-secondary">
            Tử Vi Tarot is a reflection and self-discovery product. It offers Tarot, Numerology, Natal Chart, Eastern Horoscope, and
            Tử Vi Lá Số readings, an AI conversational Companion, a personal Journal, and optional Premium features. Every reading&rsquo;s
            underlying facts (a card draw, a numerology figure, a chart placement, a Tử Vi star position) are produced by a
            deterministic calculation, never invented by AI — AI is used only to narrate or discuss a result already calculated.
          </p>
        </MvSection>

        <MvSection title="2. Not medical, psychological, financial, or legal advice">
          <p className="text-body-md text-text-secondary">
            Tử Vi Tarot is offered for reflection, entertainment, and self-discovery. It is not a medical, psychological, financial,
            or legal advice service, does not diagnose or treat any condition, and nothing in a reading, chart, or AI-generated
            interpretation should be treated as a guaranteed prediction of future events or outcomes. If you&rsquo;re in crisis,
            please contact a local emergency service or a crisis line in your region.
          </p>
        </MvSection>

        <MvSection title="3. AI-generated content">
          <p className="text-body-md text-text-secondary">
            Interpretations and Companion replies are generated by a third-party AI model. AI-generated text can be imprecise,
            incomplete, or occasionally wrong in tone or emphasis, even though the deterministic facts it&rsquo;s narrating (the card,
            the number, the chart, the star) are fixed and never altered by it. Use your own judgment; don&rsquo;t treat AI-generated
            narration as a certainty.
          </p>
        </MvSection>

        <MvSection title="4. Eligibility and account responsibility">
          <p className="text-body-md text-text-secondary">
            You need an account to use most of the product. You&rsquo;re responsible for the accuracy of the information you provide,
            for keeping your password confidential, and for activity that happens under your account.
            <OwnerPlaceholder>the minimum age required to create an account</OwnerPlaceholder>.
          </p>
        </MvSection>

        <MvSection title="5. Acceptable use">
          <p className="text-body-md text-text-secondary">
            By creating an account, you agree to use Tử Vi Tarot in good faith: not to misuse the service to harm others, not to
            attempt to bypass its security or rate limits, not to use it to generate or extract content in violation of applicable
            law, and not to attempt to access another user&rsquo;s account or data.
          </p>
        </MvSection>

        <MvSection title="6. Your content">
          <p className="text-body-md text-text-secondary">
            You retain ownership of what you write into the product — Journal entries, Companion messages, and any reflection text
            you add to a reading. We process it to provide the service to you (see the Privacy Notice), and we don&rsquo;t use it to
            train AI models without your explicit, specific, separately-requested consent. Tử Vi Tarot has no public community or
            content-sharing feature today, so nothing you write is shown to other users.
          </p>
        </MvSection>

        <MvSection title="7. Our content and intellectual property">
          <p className="text-body-md text-text-secondary">
            The Tử Vi Tarot name, product design, and the deterministic calculation engines are ours or licensed to us. Card
            imagery, calculation methodologies, and reference sources we cite are used and credited as their own terms require. You
            may not copy, resell, or redistribute the product itself.
          </p>
        </MvSection>

        <MvSection title="8. Premium and payments">
          <p className="text-body-md text-text-secondary">
            Premium is a one-time purchase that grants 30 days of access — it is not a recurring subscription, and it does not
            renew automatically; purchasing again while Premium is already active extends your access from its current expiry
            rather than restarting the clock. Payments are processed by PayOS; the exact current price is shown in-app before you
            pay and, while the product is still in its early pricing phase, may not yet be finalized.
          </p>
          <p className="mt-3 text-body-md text-text-secondary">
            <OwnerPlaceholder>the refund policy — under what circumstances, if any, a payment is refundable, and how to request one</OwnerPlaceholder>,
            and <OwnerPlaceholder>any applicable tax/invoice handling</OwnerPlaceholder>.
          </p>
        </MvSection>

        <MvSection title="9. Service availability">
          <p className="text-body-md text-text-secondary">
            We aim to keep the service available and reliable, but we don&rsquo;t guarantee uninterrupted access — features may be
            temporarily unavailable for maintenance, and AI-dependent features additionally depend on our third-party AI provider
            being available.
          </p>
        </MvSection>

        <MvSection title="10. Suspension and termination">
          <p className="text-body-md text-text-secondary">
            You can delete your account at any time from Settings (see the Privacy Notice, &ldquo;Deleting your account&rdquo;). We may suspend
            or terminate an account that violates §5 (Acceptable use). Where we do, we&rsquo;ll aim to tell you why.
          </p>
        </MvSection>

        <MvSection title="11. Disclaimers">
          <p className="text-body-md text-text-secondary">
            The service, including every calculation, chart, reading, and AI-generated interpretation, is provided &ldquo;as is,&rdquo;
            for reflection and entertainment purposes, without a warranty that any outcome, prediction, or interpretation it
            presents will be accurate, complete, or suited to a particular purpose.
          </p>
        </MvSection>

        <MvSection title="12. Limitation of liability">
          <p className="text-body-md text-text-secondary">
            <OwnerPlaceholder>the specific limitation-of-liability language appropriate to our operating entity and jurisdiction —
            not invented here, since an incorrect limitation clause can be unenforceable or actively harmful</OwnerPlaceholder>.
          </p>
        </MvSection>

        <MvSection title="13. Governing law and disputes">
          <p className="text-body-md text-text-secondary">
            <OwnerPlaceholder>the governing law and the forum/jurisdiction for resolving a dispute</OwnerPlaceholder>.
          </p>
        </MvSection>

        <MvSection title="14. Changes to these terms or the service">
          <p className="text-body-md text-text-secondary">
            We may update these terms or change, add, or remove features as the product develops. If we make a material change to
            these terms, we&rsquo;ll update the date at the top of this page.
          </p>
        </MvSection>

        <MvSection title="15. Contact">
          <p className="text-body-md text-text-secondary">
            Questions about these terms can be sent via the <a href="/contact" className="text-insight underline">Contact page</a>.
          </p>
        </MvSection>
      </MvPage>
    </main>
  );
}
