export type KnowledgeCluster = 'tu-vi' | 'tarot' | 'than-so-hoc' | 'ban-do-sao' | 'ngu-hanh';

export type KnowledgeArticle = {
  slug: string; cluster: KnowledgeCluster; title: string; description: string;
  intro: string; sections: { heading: string; body: string }[];
  cta: { label: string; href: string }; relatedSlugs?: string[]; updatedAt: string;
};

export const CLUSTERS: Record<KnowledgeCluster, { title: string; description: string; toolHref: string }> = {
  'tu-vi': { title: 'Kiến thức Tử Vi', description: 'Hiểu lá số, 12 cung, chính tinh và các lớp vận hạn trước khi tự lập lá số.', toolHref: '/discover/tu-vi' },
  tarot: { title: 'Kiến thức Tarot', description: 'Nền tảng về 78 lá Tarot, Major Arcana và cách đọc trải bài theo hướng chiêm nghiệm.', toolHref: '/discover/tarot' },
  'than-so-hoc': { title: 'Kiến thức Thần số học', description: 'Cách tính và đọc các chỉ số cốt lõi từ ngày sinh và họ tên.', toolHref: '/discover/numerology' },
  'ban-do-sao': { title: 'Kiến thức Bản đồ sao', description: 'Hành tinh, cung Hoàng đạo, nhà và góc hợp trong bản đồ sao cá nhân.', toolHref: '/discover/natal-chart' },
  'ngu-hanh': { title: 'Kiến thức Ngũ hành', description: 'Nền tảng Kim, Mộc, Thủy, Hỏa, Thổ và quan hệ sinh khắc.', toolHref: '/discover/eastern-horoscope' },
};

export const ARTICLES: KnowledgeArticle[] = [
  { slug:'la-so-tu-vi-la-gi', cluster:'tu-vi', title:'Lá số Tử Vi là gì? Cấu trúc và cách đọc cơ bản', description:'Tìm hiểu lá số Tử Vi gồm những gì, 12 cung có vai trò ra sao và nên bắt đầu đọc từ đâu.', intro:'Lá số Tử Vi là một hệ thống biểu diễn thông tin theo thời điểm sinh, tổ chức thành các cung và nhóm sao để phục vụ việc luận giải theo truyền thống Tử Vi Đẩu Số.', sections:[{heading:'Một lá số gồm những gì?',body:'Phần trung tâm của lá số là 12 cung, đi cùng hệ thống chính tinh, phụ tinh và các lớp thông tin về vận. Mỗi thành phần cần được đọc trong quan hệ với toàn cục thay vì tách riêng một sao để kết luận.'},{heading:'Nên bắt đầu đọc từ đâu?',body:'Người mới nên xác định Mệnh, Thân và các cung liên quan đến câu hỏi đang quan tâm, sau đó mới xem tổ hợp sao và vận. Kết quả luận giải nên được xem như một khung tham khảo, không phải dự đoán chắc chắn.',{heading:"Cách hiểu 12 cung",body:"Mười hai cung là các khu vực chủ đề của lá số. Khi đọc một cung, cần xem tên cung, vị trí, các sao tọa thủ và những cung tạo thành tam phương tứ chính. Một cung không nên được diễn giải như một ô độc lập, vì ý nghĩa thay đổi theo tổ hợp và bối cảnh toàn lá số."}}],cta:{label:'Lập lá số Tử Vi',href:'/discover/tu-vi'},relatedSlugs:["cach-xem-la-so-tu-vi"],updatedAt:'2026-09-26' },
  { slug:'cach-xem-la-so-tu-vi', cluster:'tu-vi', title:'Cách xem lá số Tử Vi cho người mới bắt đầu', description:'Trình tự đọc lá số Tử Vi từ Mệnh, Thân, 12 cung đến đại vận và tiểu hạn.', intro:'Đọc lá số hiệu quả cần một trình tự rõ ràng để tránh diễn giải từng sao một cách rời rạc.', sections:[{heading:'Đọc cấu trúc trước chi tiết',body:'Hãy bắt đầu từ vị trí Mệnh, Thân, tam phương tứ chính và các cung trọng tâm. Sau đó mới đi sâu vào tổ hợp chính tinh và phụ tinh.'},{heading:'Đặt vận hạn vào đúng bối cảnh',body:'Đại vận và tiểu hạn bổ sung lớp thời gian cho lá số. Chúng nên được đọc cùng cấu trúc gốc thay vì dùng riêng để đưa ra kết luận tuyệt đối.',{heading:"Một quy trình đọc thực tế",body:"Sau khi xác định Mệnh và Thân, hãy chọn câu hỏi cụ thể rồi đối chiếu cung liên quan, tam phương tứ chính và tổ hợp sao. Cuối cùng mới đặt đại vận, tiểu hạn vào bối cảnh đó. Trình tự này giúp hạn chế việc chọn một chi tiết nổi bật rồi suy rộng thành kết luận cho toàn bộ lá số."}}],cta:{label:'Xem lá số của bạn',href:'/discover/tu-vi'},relatedSlugs:["la-so-tu-vi-la-gi"],updatedAt:'2026-09-26' },
  { slug:'tarot-la-gi', cluster:'tarot', title:'Tarot là gì? Bộ bài 78 lá và cách bắt đầu', description:'Giải thích cấu trúc 78 lá Tarot, Major Arcana, Minor Arcana và cách tiếp cận một trải bài.', intro:'Tarot là bộ bài 78 lá thường được dùng như một công cụ biểu tượng để suy ngẫm về câu hỏi, cảm xúc và lựa chọn.', sections:[{heading:'78 lá Tarot được chia thế nào?',body:'Bộ bài chuẩn gồm 22 lá Major Arcana và 56 lá Minor Arcana. Major Arcana thường gắn với các chủ đề lớn, trong khi Minor Arcana đi sâu hơn vào trải nghiệm thường ngày.'},{heading:'Tarot có quyết định thay bạn không?',body:'Không. Một trải bài có thể gợi mở góc nhìn, nhưng quyết định vẫn thuộc về bạn. Cách đọc có ích nhất là đặt thông điệp vào hoàn cảnh thực tế của câu hỏi.',{heading:"Cách đặt câu hỏi khi trải bài",body:"Câu hỏi mở thường hữu ích hơn câu hỏi chỉ yêu cầu có hoặc không. Bạn có thể hỏi mình đang bỏ sót điều gì, yếu tố nào cần cân nhắc hoặc cách nhìn nào đáng thử. Tarot khi đó đóng vai trò gợi ý để phản tư, còn hành động và quyết định vẫn dựa trên hoàn cảnh thực tế."}}],cta:{label:'Trải Tarot',href:'/discover/tarot'},relatedSlugs:["y-nghia-78-la-tarot"],updatedAt:'2026-09-26' },
  { slug:'y-nghia-78-la-tarot', cluster:'tarot', title:'Ý nghĩa 78 lá Tarot: cách hiểu toàn bộ bộ bài', description:'Tổng quan cách học ý nghĩa 78 lá Tarot theo Major Arcana, Minor Arcana và bốn bộ chất.', intro:'Thay vì học thuộc 78 định nghĩa riêng lẻ, bạn có thể hiểu Tarot theo cấu trúc và mối liên hệ giữa các nhóm lá.', sections:[{heading:'Major Arcana',body:'22 lá Major Arcana tạo thành một chuỗi biểu tượng về những bước ngoặt, bài học và quá trình phát triển.'},{heading:'Minor Arcana',body:'56 lá Minor Arcana gồm bốn bộ chất. Mỗi bộ có một trường chủ đề riêng và đi từ Ace đến 10, sau đó là các lá Hoàng gia.',{heading:"Học theo hệ thống thay vì học thuộc",body:"Khi gặp một lá, hãy quan sát nhóm Major hay Minor, bộ chất, con số hoặc nhân vật Hoàng gia, rồi mới ghép với hình ảnh và vị trí trong trải bài. Cách học theo lớp giúp bạn hiểu quan hệ giữa các lá và tránh biến mỗi lá thành một câu dự đoán cố định."}}],cta:{label:'Rút bài Tarot',href:'/discover/tarot'},relatedSlugs:["tarot-la-gi"],updatedAt:'2026-09-26' },
  { slug:'than-so-hoc-la-gi', cluster:'than-so-hoc', title:'Thần số học là gì? Các chỉ số cơ bản cần biết', description:'Tìm hiểu Số chủ đạo, Sứ mệnh, Linh hồn, Nhân cách và cách các chỉ số bổ sung cho nhau.', intro:'Thần số học sử dụng các phép quy đổi số từ ngày sinh và họ tên để tạo ra một hệ chỉ số mang tính diễn giải.', sections:[{heading:'Không chỉ có Số chủ đạo',body:'Ngoài Số chủ đạo, một hồ sơ có thể gồm Sứ mệnh, Linh hồn, Nhân cách, Trưởng thành và Ngày sinh. Mỗi chỉ số trả lời một lớp câu hỏi khác nhau.'},{heading:'Số đặc biệt 11, 22, 33',body:'Trong một số trường phái, 11, 22 và 33 được giữ nguyên ở những vị trí nhất định thay vì tiếp tục rút gọn. Vì vậy công thức tính cần nhất quán trước khi diễn giải.',{heading:"Ngày sinh và họ tên đóng vai trò khác nhau",body:"Các chỉ số từ ngày sinh và các chỉ số quy đổi từ họ tên được hình thành từ dữ liệu khác nhau, vì vậy không nên coi chúng là những tên gọi khác nhau của cùng một kết quả. Khi đọc hồ sơ, nên giữ công thức nhất quán và xem các chỉ số như những lớp diễn giải bổ sung cho nhau."}}],cta:{label:'Tính các chỉ số của bạn',href:'/discover/numerology'},relatedSlugs:["so-chu-dao-la-gi","so-chu-dao-11"],updatedAt:'2026-09-26' },
  { slug:'so-chu-dao-la-gi', cluster:'than-so-hoc', title:'Số chủ đạo là gì? Cách tính từ ngày sinh', description:'Cách tính Số chủ đạo và lưu ý về các số đặc biệt 11, 22, 33.', intro:'Số chủ đạo là một trong những chỉ số được nhắc đến nhiều nhất trong thần số học và thường được tính từ toàn bộ ngày sinh.', sections:[{heading:'Nguyên tắc tính',body:'Các chữ số của ngày, tháng và năm sinh được cộng theo quy tắc của hệ thống đang sử dụng rồi rút gọn. Việc xử lý 11, 22 và 33 cần theo đúng quy ước của công cụ.'},{heading:'Đừng đọc một chỉ số riêng lẻ',body:'Số chủ đạo chỉ là một phần của hồ sơ. Khi muốn có bức tranh đầy đủ hơn, nên đọc cùng các chỉ số từ họ tên và những chỉ số bổ trợ.',{heading:"Ví dụ về cách kiểm tra phép tính",body:"Sau khi nhập ngày sinh, hãy kiểm tra lại từng chữ số và quy tắc rút gọn mà hệ thống sử dụng, đặc biệt khi tổng trung gian xuất hiện 11, 22 hoặc 33. Việc công khai quy tắc tính giúp bạn phân biệt phần kết quả số học với phần diễn giải được trình bày sau đó."}}],cta:{label:'Tính Số chủ đạo',href:'/discover/numerology'},relatedSlugs:["than-so-hoc-la-gi","so-chu-dao-11"],updatedAt:'2026-09-26' },
  { slug:'so-chu-dao-11', cluster:'than-so-hoc', title:'Số chủ đạo 11: ý nghĩa và cách hiểu số đặc biệt', description:'Tìm hiểu cách số 11 được giữ nguyên và cách đặt ý nghĩa của nó trong toàn bộ hồ sơ thần số học.', intro:'Số 11 thường được xem là một số đặc biệt trong các hệ thần số học có quy tắc giữ Master Number.', sections:[{heading:'Vì sao 11 không luôn rút thành 2?',body:'Một số phương pháp giữ nguyên 11 tại các bước tính nhất định để phân biệt sắc thái của nó với số 2 thông thường.'},{heading:'Đọc 11 trong toàn bộ hồ sơ',body:'Không nên dùng riêng số 11 để gắn nhãn tính cách hoặc tương lai. Các chỉ số khác và trải nghiệm thực tế của mỗi người vẫn là bối cảnh quan trọng.',{heading:"Điểm cần lưu ý khi gặp số 11",body:"Việc giữ 11 hay tiếp tục rút gọn phụ thuộc vào quy ước của hệ thống thần số học đang áp dụng. Vì thế hai công cụ dùng quy tắc khác nhau có thể cho cách trình bày khác nhau. Trước khi so sánh ý nghĩa, nên kiểm tra phương pháp tính và dữ liệu đầu vào."}}],cta:{label:'Kiểm tra hồ sơ số học',href:'/discover/numerology'},relatedSlugs:["so-chu-dao-la-gi","than-so-hoc-la-gi"],updatedAt:'2026-09-26' },
  { slug:'ban-do-sao-la-gi', cluster:'ban-do-sao', title:'Bản đồ sao là gì? Hành tinh, cung và 12 nhà', description:'Hiểu cấu trúc một bản đồ sao cá nhân gồm hành tinh, cung Hoàng đạo, 12 nhà và các góc hợp.', intro:'Bản đồ sao là sơ đồ vị trí các thiên thể theo thời điểm và địa điểm sinh, được chiêm tinh học dùng làm nền tảng diễn giải.', sections:[{heading:'Ba lớp thông tin chính',body:'Hành tinh thường biểu thị chức năng, cung mô tả cách biểu hiện, còn nhà cho biết lĩnh vực đời sống nơi chủ đề đó được đặt vào.'},{heading:'Góc hợp bổ sung mối quan hệ',body:'Các góc hợp mô tả quan hệ hình học giữa các vị trí trong bản đồ. Chúng được đọc cùng hành tinh, cung và nhà thay vì đứng độc lập.',{heading:"Vì sao thời gian và địa điểm quan trọng",body:"Thời điểm và địa điểm sinh được dùng để xác định bầu trời và hệ nhà tại vị trí tương ứng. Sai lệch giờ sinh có thể ảnh hưởng tới Cung Mọc và các nhà. Vì vậy nên dùng dữ liệu sinh chính xác nhất có thể và coi những trường hợp thiếu giờ sinh là có giới hạn khi diễn giải."}}],cta:{label:'Lập bản đồ sao',href:'/discover/natal-chart'},relatedSlugs:["cung-moc-la-gi"],updatedAt:'2026-09-26' },
  { slug:'cung-moc-la-gi', cluster:'ban-do-sao', title:'Cung Mọc là gì? Vai trò của Ascendant trong bản đồ sao', description:'Cung Mọc được xác định thế nào và vì sao giờ, địa điểm sinh quan trọng khi lập bản đồ sao.', intro:'Cung Mọc, hay Ascendant, là điểm Hoàng đạo đang mọc ở chân trời phía đông tại thời điểm và địa điểm được tính.', sections:[{heading:'Vì sao cần giờ sinh?',body:'Cung Mọc thay đổi theo thời gian trong ngày nên giờ sinh có ảnh hưởng trực tiếp đến phép tính. Địa điểm sinh cũng cần thiết để xác định đường chân trời địa phương.'},{heading:'Cung Mọc không thay thế toàn bộ bản đồ',body:'Đây là một điểm quan trọng nhưng không phải toàn bộ hồ sơ. Cần đọc cùng Mặt Trời, Mặt Trăng, các hành tinh, nhà và góc hợp.',{heading:"Cách đọc Cung Mọc trong bối cảnh",body:"Cung Mọc thường được đọc cùng hành tinh chủ quản của cung đó, vị trí các nhà và các góc hợp liên quan. Nếu chỉ lấy một mô tả chung về Ascendant rồi áp cho toàn bộ tính cách, bạn sẽ bỏ qua nhiều lớp thông tin khác của bản đồ sao."}}],cta:{label:'Tìm Cung Mọc của bạn',href:'/discover/natal-chart'},relatedSlugs:["ban-do-sao-la-gi"],updatedAt:'2026-09-26' },
  { slug:'ngu-hanh-la-gi', cluster:'ngu-hanh', title:'Ngũ hành là gì? Kim, Mộc, Thủy, Hỏa, Thổ và sinh khắc', description:'Nền tảng Ngũ hành và hai quan hệ tương sinh, tương khắc thường gặp trong hệ thống phương Đông.', intro:'Ngũ hành là mô hình gồm Kim, Mộc, Thủy, Hỏa và Thổ, dùng để mô tả các quan hệ vận động và chuyển hóa trong nhiều hệ tư tưởng phương Đông.', sections:[{heading:'Tương sinh',body:'Quan hệ tương sinh mô tả chu trình hỗ trợ và phát triển giữa các hành. Nó không nên được hiểu đơn giản thành “tốt tuyệt đối” trong mọi hoàn cảnh.'},{heading:'Tương khắc',body:'Tương khắc mô tả quan hệ chế ước giữa các hành. Khi ứng dụng vào luận giải cá nhân, cần đặt nó trong toàn bộ hệ thống thay vì kết luận chỉ từ một cặp hành.',{heading:"Ứng dụng sinh khắc cần có bối cảnh",body:"Tương sinh và tương khắc mô tả quan hệ giữa các hành chứ không tự động tạo ra nhãn tốt hoặc xấu cho một người. Khi một công cụ dùng ngày sinh hoặc dữ liệu khác để xác định yếu tố Ngũ hành, cần xem rõ phương pháp tính trước khi diễn giải các quan hệ sinh khắc."}}],cta:{label:'Khám phá Ngũ hành',href:'/discover/eastern-horoscope'},updatedAt:'2026-09-26' },
];

export const articleBySlug = (slug: string) => ARTICLES.find((article) => article.slug === slug);
export const articlesByCluster = (cluster: KnowledgeCluster) => ARTICLES.filter((article) => article.cluster === cluster);
