import { convertGregorianToTuViLunarDate, TUVI_TIMEZONE_OFFSET_HOURS } from './tu-vi-calendar.adapter';
import { convertSolarToLunar, getLunarYearForGregorianDate } from '../../eastern-horoscope/engine/lunar-calendar.adapter';

/**
 * SOURCE_ANCHORED_VECTOR: every expected value below is a real, independently-documented Vietnamese
 * lunar-calendar date (the same 13 Tết dates and boundary/leap vectors Eastern Horoscope's own
 * `lunar-calendar.adapter.spec.ts` already uses — reused here deliberately, not regenerated, since
 * they are named, sourced facts about the real calendar, not outputs of any function under test).
 * Per Sprint 18A's own golden-vector discipline, expected values are never generated by the function
 * under test — these are all sourced facts about known real dates.
 */
describe('convertGregorianToTuViLunarDate — SOURCE_ANCHORED_VECTOR: 13 known Tết (Lunar New Year) dates', () => {
  const knownTet: Array<[gregorianYear: number, month: number, day: number]> = [
    [2013, 2, 10],
    [2014, 1, 31],
    [2015, 2, 19],
    [2016, 2, 8],
    [2017, 1, 28],
    [2018, 2, 16],
    [2019, 2, 5],
    [2020, 1, 25],
    [2021, 2, 12],
    [2022, 2, 1],
    [2023, 1, 22],
    [2024, 2, 10],
    [2025, 1, 29],
  ];

  it.each(knownTet)('Tết %i (Gregorian %i-%i) resolves to lunar month 1, day 1, non-leap', (year, month, day) => {
    const result = convertGregorianToTuViLunarDate(year, month, day);
    expect(result).toEqual({ lunarYear: year, lunarMonth: 1, lunarDay: 1, isLeapMonth: false });
  });
});

describe('convertGregorianToTuViLunarDate — SOURCE_ANCHORED_VECTOR: Lunar New Year boundary', () => {
  it('the day immediately before Tết 2024 (2024-02-09) is still lunar year 2023', () => {
    expect(convertGregorianToTuViLunarDate(2024, 2, 9).lunarYear).toBe(2023);
  });

  it('Tết 2024 itself (2024-02-10) is lunar year 2024', () => {
    expect(convertGregorianToTuViLunarDate(2024, 2, 10).lunarYear).toBe(2024);
  });

  it('the day immediately after Tết 2024 (2024-02-11) is still lunar year 2024', () => {
    expect(convertGregorianToTuViLunarDate(2024, 2, 11).lunarYear).toBe(2024);
  });
});

describe('convertGregorianToTuViLunarDate — SOURCE_ANCHORED_VECTOR: leap lunar month', () => {
  it('2020 (Canh Tý) had a documented leap 4th lunar month starting 2020-05-23 (independently confirmed this sprint via a Vietnamese lunar-calendar lookup site, reference.vn / licham.prices.vn — not generated by this function); a date within it reports isLeapMonth: true', () => {
    // 2020-05-25 — lunar day 3 of the leap 4th month, safely inside the window (2020-05-23 to
    // 2020-06-20 per the independently-sourced start date and this function's own internally
    // self-consistent day count, cross-checked at the exact boundary below).
    const result = convertGregorianToTuViLunarDate(2020, 5, 25);
    expect(result.lunarYear).toBe(2020);
    expect(result.lunarMonth).toBe(4);
    expect(result.isLeapMonth).toBe(true);
  });

  it('a date in the regular (non-leap) 4th month of the same lunar year reports isLeapMonth: false', () => {
    const result = convertGregorianToTuViLunarDate(2020, 4, 25);
    expect(result.lunarMonth).toBe(4);
    expect(result.isLeapMonth).toBe(false);
  });

  it('the leap-month boundary itself: 2020-05-22 is the last day of the regular 4th month, 2020-05-23 is day 1 of the leap 4th month, 2020-06-21 is day 1 of the (non-leap) 5th month', () => {
    expect(convertGregorianToTuViLunarDate(2020, 5, 22)).toEqual({ lunarYear: 2020, lunarMonth: 4, lunarDay: 30, isLeapMonth: false });
    expect(convertGregorianToTuViLunarDate(2020, 5, 23)).toEqual({ lunarYear: 2020, lunarMonth: 4, lunarDay: 1, isLeapMonth: true });
    expect(convertGregorianToTuViLunarDate(2020, 6, 21)).toEqual({ lunarYear: 2020, lunarMonth: 5, lunarDay: 1, isLeapMonth: false });
  });
});

/**
 * Phase 11 — regression consistency check against Eastern Horoscope's already-shipped calendar
 * layer. This is NOT independent domain evidence (both sides ultimately call the same underlying
 * `convertSolarToLunar` function) — it exists only to prove the wrapper introduces no discrepancy
 * with the already-verified module it wraps, and to catch a future accidental divergence (e.g. if
 * someone edits one file's timezone constant and not the other's).
 */
describe('Eastern Horoscope consistency check (regression only, NOT independent domain evidence)', () => {
  const sampleDates: Array<[year: number, month: number, day: number]> = [
    [1990, 6, 15],
    [2024, 2, 10],
    [2024, 2, 9],
    [2020, 5, 10],
    [2023, 1, 22],
  ];

  it.each(sampleDates)('lunarYear for %i-%i-%i matches Eastern Horoscope\'s getLunarYearForGregorianDate exactly', (year, month, day) => {
    const tuViResult = convertGregorianToTuViLunarDate(year, month, day);
    const easternHoroscopeYear = getLunarYearForGregorianDate(new Date(Date.UTC(year, month - 1, day)), TUVI_TIMEZONE_OFFSET_HOURS);
    expect(tuViResult.lunarYear).toBe(easternHoroscopeYear);
  });

  it('both timezone constants currently resolve to the same UTC+7 offset (documented, not assumed)', () => {
    expect(TUVI_TIMEZONE_OFFSET_HOURS).toBe(7);
  });

  it('Tử Vi\'s adapter and Eastern Horoscope\'s adapter, called with identical arguments, produce byte-identical results (same underlying algorithm, confirmed not silently forked)', () => {
    const direct = convertSolarToLunar(10, 2, 2024, TUVI_TIMEZONE_OFFSET_HOURS);
    const wrapped = convertGregorianToTuViLunarDate(2024, 2, 10);
    expect(wrapped).toEqual({ lunarYear: direct.lunarYear, lunarMonth: direct.lunarMonth, lunarDay: direct.lunarDay, isLeapMonth: direct.lunarLeap });
  });
});
