import { buildTuViChart, buildPalaceProjection, validateTuViChart, TUVI_ENGINE_VERSION, TUVI_MAIN_STAR_VERSION, TUVI_AUXILIARY_VERSION, TUVI_TUAN_TRIET_VERSION, TUVI_TU_HOA_VERSION, TUVI_DIGNITY_VERSION, TUVI_CYCLE_VERSION, type TuViChart } from './tu-vi-chart';
import { TU_VI_CHINH_TINH_IDS } from './tu-vi-chinh-tinh';
import { TU_VI_CORE13_STAR_IDS } from './tu-vi-core13';
import { EARTHLY_BRANCHES } from './tu-vi-palace';

/**
 * RULE_DERIVED_TEST_VECTOR — VECTOR-B1 from `golden-vector-v2-spec.md` (Sprint 18A.5), run through
 * the COMPLETE composer end to end. Gregorian input (1984-02-02, 00:30) independently confirmed
 * this sprint to be Tết Giáp Tý 1984 (lunar month 1, day 1) — a well-known historical date, and the
 * same 1984=Giáp Tý anchor Eastern Horoscope's own table already uses — NOT generated by this
 * function under test; only the calendar-layer mapping (already verified in `tu-vi-calendar.adapter.spec.ts`)
 * was used to find a real Gregorian date matching B1's lunar design target.
 */
describe('buildTuViChart — VECTOR-B1 full end-to-end regression', () => {
  const chart = buildTuViChart({ birthDate: '1984-02-02', birthTime: '00:30', sex: 'Nam' });

  it('calendar layer', () => {
    expect(chart.calendar.lunarDate).toEqual({ lunarYear: 1984, lunarMonth: 1, lunarDay: 1, isLeapMonth: false });
    expect(chart.calendar.hourBranch).toBe('Tý');
  });

  it('Can Chi, Mệnh, Thân, Cục', () => {
    expect(chart.canChi.year).toEqual({ stem: 'Giáp', branch: 'Tý' });
    expect(chart.palaces.menh).toBe('Dần');
    expect(chart.palaces.than).toBe('Dần');
    expect(chart.cuc).toBe('Hỏa Lục Cục');
  });

  it('14 Chính Tinh', () => {
    const byStar = Object.fromEntries(chart.mainStars.map((p) => [p.star, p.position]));
    expect(byStar).toEqual({
      'Tử Vi': 'Dậu', 'Liêm Trinh': 'Sửu', 'Thiên Đồng': 'Thìn', 'Vũ Khúc': 'Tỵ', 'Thái Dương': 'Ngọ', 'Thiên Cơ': 'Thân',
      'Thiên Phủ': 'Mùi', 'Thái Âm': 'Thân', 'Tham Lang': 'Dậu', 'Cự Môn': 'Tuất', 'Thiên Tướng': 'Hợi', 'Thiên Lương': 'Tý', 'Thất Sát': 'Sửu', 'Phá Quân': 'Tỵ',
    });
  });

  it('CORE_13 (table-lookup and 0-offset stars)', () => {
    const byStar = Object.fromEntries(chart.auxiliaryStars.map((p) => [p.star, p.position]));
    expect(byStar['Lộc Tồn']).toBe('Dần');
    expect(byStar['Kình Dương']).toBe('Mão');
    expect(byStar['Đà La']).toBe('Sửu');
    expect(byStar['Thiên Khôi']).toBe('Sửu');
    expect(byStar['Thiên Việt']).toBe('Mùi');
    expect(byStar['Tả Phù']).toBe('Thìn');
    expect(byStar['Hữu Bật']).toBe('Tuất');
    expect(byStar['Văn Xương']).toBe('Tuất');
    expect(byStar['Văn Khúc']).toBe('Thìn');
    expect(byStar['Địa Kiếp']).toBe('Hợi');
    expect(byStar['Địa Không']).toBe('Hợi');
  });

  it('Tuần, Triệt', () => {
    expect(chart.tuan).toEqual({ first: 'Tuất', second: 'Hợi' });
    expect(chart.triet).toEqual({ first: 'Thân', second: 'Dậu' });
  });

  it('Tứ Hóa', () => {
    const byTransform = Object.fromEntries(chart.transformations.map((t) => [t.transformation, t.targetStar]));
    expect(byTransform).toEqual({ 'Hóa Lộc': 'Liêm Trinh', 'Hóa Quyền': 'Phá Quân', 'Hóa Khoa': 'Vũ Khúc', 'Hóa Kỵ': 'Thái Dương' });
  });

  it('Miếu/Vượng/Đắc/Hãm dignity is attached to every main star (spot-check against VDTTL-1956 p.33/34)', () => {
    const byStar = Object.fromEntries(chart.mainStars.map((p) => [p.star, p.dignity]));
    expect(byStar['Tử Vi']).toBe('Bình hòa'); // Dậu
    expect(byStar['Liêm Trinh']).toBe('Đắc địa'); // Sửu
  });

  it('Đại Vận starts at Mệnh with the Cục number, dương nam here so thuận', () => {
    expect(chart.daiVan[0]).toMatchObject({ ageStart: 6, ageEnd: 15, role: 'Mệnh', position: 'Dần' });
    expect(chart.daiVan[1]).toMatchObject({ ageStart: 16, ageEnd: 25, role: 'Phụ Mẫu' });
  });

  it('Tiểu Hạn start palace is deterministic for this chart\'s birth-year branch and sex', () => {
    expect(chart.tieuHanStart).toEqual({ startPalace: 'Tuất', thuan: true });
  });

  it('passes the full invariant suite', () => {
    expect(() => validateTuViChart(chart)).not.toThrow();
  });
});

describe('buildTuViChart — version bundle', () => {
  it('contains all 9 required version identifiers with exact expected values', () => {
    const chart = buildTuViChart({ birthDate: '2024-02-10', birthTime: '10:30', sex: 'Nam' });
    expect(chart.versions).toEqual({
      rulesetVersion: 'vdttl-1956-v1',
      calendarVersion: 'tuvi-calendar-hnd-v1',
      engineVersion: TUVI_ENGINE_VERSION,
      mainStarVersion: TUVI_MAIN_STAR_VERSION,
      auxiliaryVersion: TUVI_AUXILIARY_VERSION,
      tuanTrietVersion: TUVI_TUAN_TRIET_VERSION,
      tuHoaVersion: TUVI_TU_HOA_VERSION,
      dignityVersion: TUVI_DIGNITY_VERSION,
      cycleVersion: TUVI_CYCLE_VERSION,
    });
  });
});

describe('buildTuViChart — determinism', () => {
  it('repeated calls with identical input produce deep-equal charts (no Date.now/random/env dependency)', () => {
    const input = { birthDate: '1990-06-15', birthTime: '03:20', sex: 'Nữ' as const };
    const first = buildTuViChart(input);
    for (let i = 0; i < 10; i++) {
      expect(buildTuViChart(input)).toEqual(first);
    }
  });

  it('is frozen at every level (input, calendar, canChi, palaces, versions)', () => {
    const chart = buildTuViChart({ birthDate: '1990-06-15', birthTime: '03:20', sex: 'Nữ' });
    expect(Object.isFrozen(chart)).toBe(true);
    expect(Object.isFrozen(chart.input)).toBe(true);
    expect(Object.isFrozen(chart.calendar)).toBe(true);
    expect(Object.isFrozen(chart.canChi)).toBe(true);
    expect(Object.isFrozen(chart.palaces)).toBe(true);
    expect(Object.isFrozen(chart.versions)).toBe(true);
  });
});

describe('buildPalaceProjection', () => {
  const chart = buildTuViChart({ birthDate: '1984-02-02', birthTime: '00:30', sex: 'Nam' });
  const projection = buildPalaceProjection(chart);

  it('has exactly 12 entries, one per EarthlyBranch, in canonical order', () => {
    expect(projection).toHaveLength(12);
    expect(projection.map((e) => e.branch)).toEqual([...EARTHLY_BRANCHES]);
  });

  it('exactly one entry is marked isMenh and it matches chart.palaces.menh', () => {
    const menhEntries = projection.filter((e) => e.isMenh);
    expect(menhEntries).toHaveLength(1);
    expect(menhEntries[0]?.branch).toBe(chart.palaces.menh);
  });

  it('a dense palace (Tý, VECTOR-B1) correctly lists both its main star (Thiên Lương) and CORE_13 stars together', () => {
    const tyEntry = projection.find((e) => e.branch === 'Tý')!;
    expect(tyEntry.mainStars).toContain('Thiên Lương');
  });

  it('is a pure derived view — mutating it does not affect the underlying chart, and it is itself frozen', () => {
    expect(Object.isFrozen(projection)).toBe(true);
    expect(Object.isFrozen(projection[0])).toBe(true);
  });
});

/**
 * Invariant suite — mutation-tested. Each test constructs a shallow-mutated copy of a valid chart
 * and confirms `validateTuViChart` actually rejects that specific violation, not just that it
 * accepts valid input (a validator that never rejects anything would otherwise pass silently).
 */
describe('validateTuViChart — invariant suite (mutation-tested)', () => {
  const validChart = buildTuViChart({ birthDate: '1984-02-02', birthTime: '00:30', sex: 'Nam' });

  it('accepts a genuinely valid chart', () => {
    expect(() => validateTuViChart(validChart)).not.toThrow();
  });

  it('rejects an invalid Cục value', () => {
    const broken = { ...validChart, cuc: 'Not A Real Cục' } as unknown as TuViChart;
    expect(() => validateTuViChart(broken)).toThrow(/Cục/);
  });

  it('rejects a main-star array with a duplicate star ID', () => {
    const broken = { ...validChart, mainStars: [...validChart.mainStars.slice(0, -1), validChart.mainStars[0]] } as unknown as TuViChart;
    expect(() => validateTuViChart(broken)).toThrow(/main-star/);
  });

  it('rejects a main-star array with fewer than 14 entries', () => {
    const broken = { ...validChart, mainStars: validChart.mainStars.slice(0, 13) } as unknown as TuViChart;
    expect(() => validateTuViChart(broken)).toThrow(/14/);
  });

  it('rejects an auxiliary-star array with a duplicate star ID', () => {
    const broken = { ...validChart, auxiliaryStars: [...validChart.auxiliaryStars.slice(0, -1), validChart.auxiliaryStars[0]] } as unknown as TuViChart;
    expect(() => validateTuViChart(broken)).toThrow(/CORE_13/);
  });

  it('rejects Tuần with both palaces identical', () => {
    const broken = { ...validChart, tuan: { first: 'Tý', second: 'Tý' } } as unknown as TuViChart;
    expect(() => validateTuViChart(broken)).toThrow(/Tuần/);
  });

  it('rejects Triệt with both palaces identical', () => {
    const broken = { ...validChart, triet: { first: 'Sửu', second: 'Sửu' } } as unknown as TuViChart;
    expect(() => validateTuViChart(broken)).toThrow(/Triệt/);
  });

  it('rejects a transformations array missing one of the 4 required transformations', () => {
    const broken = { ...validChart, transformations: validChart.transformations.slice(0, 3) } as unknown as TuViChart;
    expect(() => validateTuViChart(broken)).toThrow(/4/);
  });

  it('rejects a palace layout with fewer than 12 roles', () => {
    const brokenLayout = { ...validChart.palaces.layout };
    delete (brokenLayout as Record<string, unknown>)['Hợi'];
    const broken = { ...validChart, palaces: { ...validChart.palaces, layout: brokenLayout } } as unknown as TuViChart;
    expect(() => validateTuViChart(broken)).toThrow(/12/);
  });

  it('rejects an incomplete version bundle', () => {
    const broken = { ...validChart, versions: { ...validChart.versions, engineVersion: '' } } as unknown as TuViChart;
    expect(() => validateTuViChart(broken)).toThrow(/version/);
  });

  it('rejects an out-of-range position value', () => {
    const broken = { ...validChart, palaces: { ...validChart.palaces, menh: 'NotABranch' } } as unknown as TuViChart;
    expect(() => validateTuViChart(broken)).toThrow(/position/);
  });
});

describe('buildTuViChart — broad invariant coverage across many real inputs', () => {
  const sampleInputs: Array<{ birthDate: string; birthTime: string; sex: 'Nam' | 'Nữ' }> = [
    { birthDate: '1990-06-15', birthTime: '03:20', sex: 'Nam' },
    { birthDate: '1990-11-25', birthTime: '14:00', sex: 'Nữ' },
    { birthDate: '2000-01-01', birthTime: '00:00', sex: 'Nam' },
    { birthDate: '2020-06-20', birthTime: '23:30', sex: 'Nữ' },
    { birthDate: '2020-06-21', birthTime: '00:30', sex: 'Nam' },
    { birthDate: '2024-02-09', birthTime: '12:00', sex: 'Nữ' },
    { birthDate: '2024-02-10', birthTime: '12:00', sex: 'Nam' },
  ];

  it.each(sampleInputs)('produces a fully valid chart for %j', (input) => {
    const chart = buildTuViChart(input);
    expect(() => validateTuViChart(chart)).not.toThrow();
  });

  it('every main star ID belongs to TU_VI_CHINH_TINH_IDS and every auxiliary star ID to TU_VI_CORE13_STAR_IDS, across all sample inputs', () => {
    for (const input of sampleInputs) {
      const chart = buildTuViChart(input);
      expect(chart.mainStars.every((s) => (TU_VI_CHINH_TINH_IDS as readonly string[]).includes(s.star))).toBe(true);
      expect(chart.auxiliaryStars.every((s) => (TU_VI_CORE13_STAR_IDS as readonly string[]).includes(s.star))).toBe(true);
    }
  });
});
