import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ARTICLES, articleBySlug, CLUSTERS, type KnowledgeCluster } from '@/features/knowledge/content';
import { buildMetadata, SITE_NAME, SITE_URL } from '@/lib/seo';

type Props={params:Promise<{cluster:string;slug:string}>};
export function generateStaticParams(){return ARTICLES.map(a=>({cluster:a.cluster,slug:a.slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {cluster,slug}=await params; const a=articleBySlug(slug); if(!a||a.cluster!==cluster)return {}; return buildMetadata({title:a.title,description:a.description,path:`/kien-thuc/${cluster}/${slug}`});}
export default async function ArticlePage({params}:Props){const {cluster,slug}=await params; const a=articleBySlug(slug); const c=CLUSTERS[cluster as KnowledgeCluster]; if(!a||!c||a.cluster!==cluster)notFound(); const url=`${SITE_URL}/kien-thuc/${cluster}/${slug}`; const jsonLd={'@context':'https://schema.org','@type':'Article',headline:a.title,description:a.description,dateModified:a.updatedAt,datePublished:a.updatedAt,mainEntityOfPage:url,author:{'@type':'Organization',name:SITE_NAME,url:SITE_URL},publisher:{'@type':'Organization',name:SITE_NAME,url:SITE_URL}}; const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Kiến thức',item:`${SITE_URL}/kien-thuc`},{'@type':'ListItem',position:2,name:c.title,item:`${SITE_URL}/kien-thuc/${cluster}`},{'@type':'ListItem',position:3,name:a.title,item:url}]}; return <article className="mx-auto min-w-0 max-w-3xl px-4 py-10 sm:px-6 lg:py-16"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumb)}}/><nav className="text-sm text-muted-foreground"><Link href="/kien-thuc">Kiến thức</Link> / <Link href={`/kien-thuc/${cluster}`}>{c.title}</Link></nav><header className="mt-6"><h1 className="break-words text-4xl font-semibold leading-tight sm:text-5xl">{a.title}</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">{a.description}</p><p className="mt-3 text-sm text-muted-foreground">Cập nhật {new Date(a.updatedAt+'T00:00:00').toLocaleDateString('vi-VN')}</p></header><div className="mt-10 space-y-9 text-[17px] leading-8"><p>{a.intro}</p>{a.sections.map(s=><section key={s.heading}><h2 className="text-2xl font-semibold">{s.heading}</h2><p className="mt-3 text-muted-foreground">{s.body}</p></section>)}</div><aside className="mt-12 rounded-2xl border border-border bg-card p-6"><p className="font-semibold">Từ kiến thức đến trải nghiệm cá nhân</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Công cụ Mệnh Vi dùng dữ liệu bạn nhập để tính kết quả; phần diễn giải mang tính tham khảo và không thay thế quyết định của bạn.</p><Link href={a.cta.href} className="mt-5 inline-flex rounded-xl bg-foreground px-5 py-3 font-semibold text-background">{a.cta.label}</Link></aside></article>}
